### PR TITLE
Add first test cases

### PR DESCRIPTION
**Pull request by AObuchow**
#3

### CODE REVIEW

**Comment by AObuchow** [comment]
@mickaelistria I just changed the Java version to 11 since `Files.readString()` was added in Java 11 and this was causing your patch to not build correctly.

I need to update the Java version being used on CI now to 11 for it to build correctly.

**Comment by mickaelistria** [comment]
I don't think we should change Java version to 11 as a lot of users are still using Java 8 and m2e itself is targeting Java 8. We should instead change the code to be compatible with Java 8.

**Comment by AObuchow** [comment]
> I don't think we should change Java version to 11 as a lot of users are still using Java 8 and m2e itself is targeting Java 8. We should instead change the code to be compatible with Java 8.

Ok good point. Another alternative would be to make the test suite into it's own bundle to get compiled with Java 11 for convenience but have the rest of the project be Java 8. This is a bit more work though so it's not really necessary.

**Comment by AObuchow** [comment]
@mickaelistria Thanks for starting the test suite!

**Pull request merged**
