### PR TITLE
Improve groupId completion

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by AObuchow** [comment]
This looks good to me except it might conflict with https://github.com/AObuchow/lsp4xml-extensions-maven/pull/62, I can merge this one first if you'd like

**Comment by mickaelistria** [comment]
Whatever works best for you.

**Comment by AObuchow** [comment]
> Whatever works best for you.

Ok, I merged the other one. This one will have to be rebased & conflicts resolved.

**Comment by mickaelistria** [comment]
I just rebased it.

**Comment by AObuchow** [comment]
> I just rebased it.

Thanks! Looks good to me & no regressions when running test locally. Merging.

**Pull request merged**
